[0m19:44:38.057052 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76f11442c0a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76f113dbf160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76f1130cf280>]}


============================== 19:44:38.060363 | 224bcc36-d850-46b8-9d0b-ee7be8173553 ==============================
[0m19:44:38.060363 [info ] [MainThread]: Running with dbt=1.8.0-b3
[0m19:44:38.060903 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/teddy/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:45:21.968355 [debug] [MainThread]: Starter project path: /home/teddy/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m19:45:21.975390 [info ] [MainThread]: 
Your new dbt project "data_warehouse" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:45:21.976374 [info ] [MainThread]: Setting up your profile.
[0m19:45:21.977782 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m19:45:21.981593 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 43.96682, "process_user_time": 0.791443, "process_kernel_time": 0.159371, "process_mem_max_rss": "73704", "process_in_blocks": "51168", "process_out_blocks": "72", "command_success": false}
[0m19:45:21.985249 [debug] [MainThread]: Command `dbt init` failed at 19:45:21.984464 after 43.97 seconds
[0m19:45:21.987313 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76f11442c0a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76f1131104c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76f1130fb7f0>]}
[0m19:45:21.990964 [debug] [MainThread]: Flushing usage events

